-- Update quantity field for Extra catering products based on product name mapping
-- This update uses case-insensitive exact matching for each product name

DO $$
DECLARE
    item record;
BEGIN
    -- Create a temporary table to store our mapping
    CREATE TEMP TABLE quantity_mapping (
        pattern text,
        qty text
    );

    -- Insert all mappings from quantity.json
    INSERT INTO quantity_mapping (pattern, qty) VALUES
    ('BOURNVITA / HORLICKS / COMPLAN', '200 ml'),
    ('BUTTERMILK (FRUIT JUICE II)', '200 ml'),
    ('LIME JUICE (FRUIT JUICE II)', '200 ml'),
    ('LASSI SWEET', '200 ml'),
    ('SEASONAL FRUIT JUICE (FRUIT JUICE I)', '200 ml'),
    ('TRAY POT TEA / COFFEE', 'Per Head'),
    ('TRAY POT TEA / COFFEE WITH BISCUITS', 'Per Head'),
    ('GREEN TEA / ASSORTED TEA', 'Per Head'),
    ('BATATA WADA', '2 pcs'),
    ('CHEESE CHILLI TOAST', '4 pcs'),
    ('CHEESE SANDWICH', '4 pcs'),
    ('COCKTAIL SAMOSA', '5 pcs'),
    ('FINGER CHIPS', '1 plate'),
    ('MIX VEG PAKODA', '10 pcs'),
    ('PANEER PAKODA', '7 pcs'),
    ('PUNJABI SAMOSA', '2 pcs'),
    ('SABUDANA WADA', '2 pcs'),
    ('STUFFED SANDWICH', '4 pcs'),
    ('VEG BURGER', '1 pcs'),
    ('VEG CUTLET', '2 pcs'),
    ('VEG GRILLED SANDWICH', '4 pcs'),
    ('VEG SANDWICH', '4 pcs'),
    ('CHICKEN CROISSANT', '1 pcs'),
    ('CHICKEN HOT DOG ROLL', '1 pcs'),
    ('CHICKEN SANDWICH', '1 pcs'),
    ('CHICKEN QUICHE', '2 pcs'),
    ('CHICKEN VOL AU VENT', '2 pcs'),
    ('HAM', '2 slice'),
    ('BACON', '2 slice'),
    ('PORK SALAMI', '2 slice'),
    ('CHICKEN SALAMI', '2 slice'),
    ('CHICKEN SAUSAGES', '2 pcs'),
    ('PORK SAUSAGES', '2 pcs'),
    ('ALOO TIKKI', '2 pcs'),
    ('ASSORTED CANAPES', '6 pcs'),
    ('BHEL PURI CHAAT', '1 plate'),
    ('CHATPATE ALOO', '6 pcs'),
    ('CHEESE BALLS', '8 pcs'),
    ('CHEESE CHERRY PINEAPPLE STICKS', '12 pcs'),
    ('DAHI BATATA PURI', '5 pcs'),
    ('DELHI CHAAT', '5 pcs'),
    ('HARA BHARA KEBAB', '6 pcs'),
    ('LAKHNAVI CHAAT', 'Per Head'),
    ('PANCHRANGI KEBAB', '8 pcs'),
    ('PANEER TIKKA', '8 pcs'),
    ('PANI PURI', '5 pcs'),
    ('PAV BHAJI', '2 pcs'),
    ('ROASTED PAPAD', '1 pcs'),
    ('SHEV BATATA PURI', '5 pcs'),
    ('VEG GOLD COIN', '6 pcs'),
    ('VEG HARIYALI KEBAB', '8 pcs'),
    ('VEG MANCHURIAN', '8 pcs'),
    ('VEG SEEKH KEBAB', '8 pcs'),
    ('TANDOORI MUSHROOM BABYCORN', '6 pcs'),
    ('CRISPY VEG', '8 pcs'),
    ('MUSHROOM BABYCORN TIKKI', '8 pcs'),
    ('FRESH CORN TIKKI', '8 pcs'),
    ('BOILED PEANUTS', '1 plate'),
    ('MASALA PEANUTS', '1 plate'),
    ('BOILED CHANA', '1 plate'),
    ('MASALA CHANA', '1 plate'),
    ('POP CORN', '1 plate'),
    ('CHANDNI KEBAB', '8 pcs'),
    ('SHAMI KEBAB', '6 pcs'),
    ('CHICKEN AFGANI KEBAB', '8 pcs'),
    ('MURGH MALAI KEBAB', '8 pcs'),
    ('CHICKEN TIKKA', '8 pcs'),
    ('CHICKEN SEEKH KEBAB', '8 pcs'),
    ('CHICKEN PAHADI KEBAB', '8 pcs'),
    ('CHICKEN BALLS', '8 pcs'),
    ('CHICKEN RESHMI KEBAB', '8 pcs'),
    ('CHICKEN GINGER FLAKES', '8 pcs'),
    ('FRIED CHICKEN', '1 full'),
    ('ROASTED CHICKEN', '8 pcs'),
    ('TANDOORI CHICKEN', '1 full'),
    ('CHICKEN BANJARA KEBAB', '8 pcs'),
    ('JEERA ONION CHICKEN TIKKA', '8 pcs'),
    ('CHICKEN ANISE TIKKA', '8 pcs'),
    ('CHICKEN CHILLI', '8 pcs'),
    ('CHICKEN MANCHURIAN', '8 pcs'),
    ('CHICKEN LOLLY POP', '8 pcs'),
    ('CHICKEN SCHEZWAN FRIES', '8 pcs'),
    ('FISH FINGER (SURMAI)', '8 pcs'),
    ('FISH FINGER (BASA)', '8 pcs'),
    ('FISH TIKKA (SURMAI)', '8 pcs'),
    ('FISH TIKKA (ROHU/KATLA)', '8 pcs'),
    ('FRIED FISH (SURMAI)', '1 pcs'),
    ('FRIED FISH (POMPFRET)', '200 grm'),
    ('FRIED FISH (OTHER)', '1 pcs'),
    ('TANDOORI POMFRET', '1 full'),
    ('TAWA FISH (SURMAI)', '1 pcs'),
    ('TAWA FISH (POMPFRET)', '200 grm'),
    ('FISH KOLIWADA', '8 pcs'),
    ('PRAWNS CHILLY / PRAWNS MANCHURIAN', '8 pcs'),
    ('ANY CHINESE VEG PREPARATION', 'Unlimited'),
    ('ANY INDIAN VEG PREPARATION', 'Unlimited'),
    ('ANY ITALIAN VEG PREPARATION', 'Unlimited'),
    ('ANY MEXICAN VEG PREPARATION', 'Unlimited'),
    ('ANY CONTINENTAL VEG PREPARATION', 'Unlimited'),
    ('BOILED VEG', 'Unlimited'),
    ('RICE PREPARATION', 'Unlimited'),
    ('EXTRA FRUITS', 'Unlimited'),
    ('FRUIT DISPLAY', '1 set'),
    ('PAPAD', 'Unlimited'),
    ('ANY SALAD PREPARATION', 'Unlimited'),
    ('FRUIT BASKET', '1 plate'),
    ('ALL FLAVOURED PUDDINGS', 'Unlimited'),
    ('ALL FLAVOURED SOUFFLES', 'Unlimited'),
    ('AMRAKHAND', 'Unlimited'),
    ('AAMRAS', 'Unlimited'),
    ('ANGOORI RABADI', 'Unlimited'),
    ('DOODHI HALWA', 'Unlimited'),
    ('GAJAR HALWA', 'Unlimited'),
    ('GULAB JAMUN', 'Unlimited'),
    ('ICE CREAM (VANILLA / CHOCOLATE)', 'Unlimited'),
    ('VANILLA ICE CREAM WITH BROWNIE', 'Unlimited'),
    ('VANILLA ICE CREAM WITH HONEY GLAZED NOODLES', 'Unlimited'),
    ('ICE CREAM (ORANGE / STRAWBERRY / KESAR PISTA)', 'Unlimited'),
    ('JAKE SHAHI', 'Unlimited'),
    ('JALEBI', 'Unlimited'),
    ('KULFI', 'Unlimited'),
    ('RASGULLA', '1 pcs'),
    ('RASMALAI', '1 pcs'),
    ('SHAHI TUKRA', 'Unlimited'),
    ('SRIKHAND', 'Unlimited'),
    ('FRESH FRUIT GATEAUX', 'Unlimited'),
    ('MOONG DAL HALWA', 'Unlimited'),
    ('JALEBI WITH RABADI', 'Unlimited'),
    ('SEVAI PAYSAM', 'Unlimited'),
    ('APPLE KHEER', 'Unlimited'),
    ('RICE KHEER', 'Unlimited'),
    ('DRY SWEETS (CHAMCHAM,SANDES,MALAI SANDWICH)', 'Unlimited'),
    ('MALAI BURFI', 'Unlimited'),
    ('ANY CHINESE NON VEG PREPARATION', 'Unlimited'),
    ('ANY INDIAN NON VEG PREPARATION', 'Unlimited'),
    ('ANY ITALIAN NON VEG PREPARATION', 'Unlimited'),
    ('ANY MEXICAN NON VEG PREPARATION', 'Unlimited'),
    ('ANY CONTINENTAL NON VEG PREPARATION', 'Unlimited'),
    ('ANY THAI NON VEG PREPARATION', 'Unlimited'),
    ('NON VEG SOUP', 'Unlimited'),
    ('WORKING LUNCH', 'Unlimited'),
    ('SHREWSBURY BISCUITS (500 GM)', '500 grm'),
    ('ICING CAKE VANILLA / PINEAPPLE (WITH EGG) 500 GM', '500 grm'),
    ('ICING CAKE VANILLA / PINEAPPLE (EGGLESS) 500 GM', '500 grm'),
    ('ICING CAKE BUTTER SCOTCH / BLUEBERRY / MANGO (WITH EGG) 500 GRM', '500 grm'),
    ('ICING CAKE BUTTER SCOTCH / BLUEBERRY / MANGO ( EGGLESS) 500 GRM', '500 grm'),
    ('COOKIES (1 KGS)', '1 Kg'),
    ('COOKIES (250 GMS)', '250 grm'),
    ('MUFFINS', '1 pcs'),
    ('TART', '1 pcs'),
    ('CALZONE', '1 pcs'),
    ('GINGER BREAD / CAKE (1KG)', '1 Kg'),
    ('DRY CAKE (1 KG)', '1 Kg'),
    ('DRY CAKE (250 GRM)', '250 grm'),
    ('DRY CAKES (WALNUTS, DRY FRUITS)', '1 Kg'),
    ('DRY FRUITS', '1 Kg'),
    ('CHOCOLATES', '6 pcs');

    -- Update products table using our mapping for Extra package only
    FOR item IN SELECT * FROM quantity_mapping LOOP
        UPDATE public.products
        SET 
            quantity = item.qty,
            updated_at = NOW()
        WHERE 
            package_id = (SELECT id FROM packages WHERE type = 'Extra' LIMIT 1)
            AND UPPER(name) = item.pattern;
    END LOOP;

    -- Clean up
    DROP TABLE quantity_mapping;
END $$;

-- Verification queries
SELECT 
    name,
    quantity,
    (SELECT name FROM packages WHERE id = package_id) as package_name
FROM public.products 
WHERE package_id = (SELECT id FROM packages WHERE type = 'Extra' LIMIT 1)
AND quantity IS NOT NULL 
ORDER BY name;