-- Create enum for check-in status
CREATE TYPE check_in_status AS ENUM ('pending', 'checked_in', 'checked_out');

-- Create participants table
CREATE TABLE participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendee_number VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create check-in records table
CREATE TABLE check_in_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT REFERENCES participants(id) ON DELETE CASCADE,
    security_check_in TIMESTAMP WITH TIME ZONE,
    reception_check_in TIMESTAMP WITH TIME ZONE,
    reception_check_out TIMESTAMP WITH TIME ZONE,
    security_check_out TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
); 